### ISSUE TITLE
Curiosity: Why not webpack-dev-server?

### ISSUE THREAD

**Issue by shellscape** [SinanMtl/webpack-simple-starter#1]
Saw this trending on HN, congrats :)

Out of curiosity, I'd like to ask why you chose to roll your own `dev-server.js` script, rather than use `webpack-dev-server`. I maintain that part of `webpack `at the moment, and I was curious not only in the decision, but if there were any deeper reasons behind it, and if we might be able to get `webpack-dev-server` get to a better state.

Cheers 🍻

**Comment by SinanMtl** [comment]
No, There aren't any reason. I haven't used the `webpack-dev-server` before but I will try. I just created this project today.
Thank you for asking 😊
